### PR TITLE
fix handling of alpha=0

### LINKED ISSUE #1: color('rgba(0, 0, 0, 0)') returns alpha of one due to zero being falsy in parseFloat(obj[3] || 1)
At this line: https://github.com/andyjansson/css-color-converter/blob/master/index.js#L94

You can repro by evaluating:
```
> Color([0, 0, 0, 0]).values
[0, 0, 0, 1]
```

### PR DESCRIPTION
**Pull request by jedwards1211**
fix #1

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -91,7 +91,7 @@ var Color = function (obj) {
 			Math.min(parseInt(obj[0]), 255),
 			Math.min(parseInt(obj[1]), 255),
 			Math.min(parseInt(obj[2]), 255),
-			parseFloat(obj[3] || 1)
+			obj[3] == null ? 1 : parseFloat(obj[3])
```
Comment (andyjansson) [inline index.js:94]: Nice catch! You might also want to add a test to prevent future regression. 
Looking at it, `parsefloat(obj[3]) || 1` (externalising the OR) would have the same effect as the null check, no?

Comment (jedwards1211) [reply index.js:94]: No, because `parseFloat('0') || 1` evaluates to 1 :)  I'll add a test

**Comment by jedwards1211** [comment]
okay, tests added

**Comment by jedwards1211** [comment]
man, I never realized that `assert` was a builtin.  Pretty cool that you have tests with zero `devDependencies`!

**Comment by jedwards1211** [comment]
Would you mind publishing this?  Otherwise I need to start publishing a fork with a scoped package name
